// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase configuration

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ2PXa8jarX2HuAFSv9JViAvMpOnhjZbk',
    appId: '1:20639293037:web:59c0f8c8932ccdf87f2964',
    messagingSenderId: '20639293037',
    projectId: 'evcharging-aef0c',
    authDomain: 'evcharging-aef0c.firebaseapp.com',
    storageBucket: 'evcharging-aef0c.firebasestorage.app',
    measurementId: 'G-1DRR840LRT',
  );

  // You need to get these values from your Firebase Console

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSaqGIrGv7eISdNxR10S6m1kGd4Bco0C8',
    appId: '1:20639293037:android:08c72f1aa07433ce7f2964',
    messagingSenderId: '20639293037',
    projectId: 'evcharging-aef0c',
    storageBucket: 'evcharging-aef0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEmvQ_m1L-xLxqtMOipL6dfXDPhQBPpa0',
    appId: '1:20639293037:ios:c5a3c37f0d11e4767f2964',
    messagingSenderId: '20639293037',
    projectId: 'evcharging-aef0c',
    storageBucket: 'evcharging-aef0c.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEmvQ_m1L-xLxqtMOipL6dfXDPhQBPpa0',
    appId: '1:20639293037:ios:c5a3c37f0d11e4767f2964',
    messagingSenderId: '20639293037',
    projectId: 'evcharging-aef0c',
    storageBucket: 'evcharging-aef0c.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ2PXa8jarX2HuAFSv9JViAvMpOnhjZbk',
    appId: '1:20639293037:web:59c0f8c8932ccdf87f2964',
    messagingSenderId: '20639293037',
    projectId: 'evcharging-aef0c',
    authDomain: 'evcharging-aef0c.firebaseapp.com',
    storageBucket: 'evcharging-aef0c.firebasestorage.app',
    measurementId: 'G-1DRR840LRT',
  );

} 